apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-deploy
  labels:
    app: playlist 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist 
  template:
    metadata:
      labels:
        app: playlist 
    spec:
      containers:
        - name: k8s-playlist
          image: matsandy/playlist:latest
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-service
spec:
  type: NodePort
  selector:
    app: playlist 
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80 
      nodePort: 31790  

