apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-deploy
  labels:
    apps: playlist
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: playlist
  template:
    metadata:
      labels:
        apps: playlist
    spec:
        containers:
          - name: k8s-playlist
            image: matsandy/playlist:latest
            ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: playlist-service
spec:
  type: NodePort
  selector:
    apps: playlist
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31790
